### ISSUE TITLE
s3 source PutObject method seems to be broken? 

### ISSUE THREAD

**Issue by ragaskar** [dpb587/metalink#4]
Hi Danny 👋  -- hope you're well! 

I tried to specify a metalink-repository-resource w/ Concourse that had a configuration something like this: 

```
- name: some-metalinks-and-files
    source:
      mirror_files:
        - destination: s3://s3.amazonaws.com/some-bucket/{{.Version}}/{{.Name}}
      options:
        access_key: ((some_aws.username))
        secret_key: ((some_aws.password))
      uri: s3://s3.amazonaws.com/some-bucket/
      url_handlers:
        - include:
            - (s3|https)://.*
          options:
            access_key: ((some_aws.username))
            secret_key: ((some_aws.password))
          type: s3
    type: metalink-repository
```

This correctly mirrors files to S3 and writes a meta4 file BUT the meta4 file is 0 bytes (which causes the subsequent GET to fail with a `in: bad repository: load: Unmarshaling: Unmarshaling XML: EOF` error.) 

When I configure this resource to store the metalink files in a github repo, everything works as expected. 

After digging into why this is happening, I think [this line](https://github.com/dpb587/metalink/blob/578c916bbfbd4c1469fdd1104c4ab57f55eed3e3/repository/source/s3/source.go#L90) in repository/s3/source.go is the culprit. 

It calls PutObject on the client, which is presumedly the minio-go S3 Sdk: 

`s.client.PutObject(s.bucket, path.Join(s.prefix, name), data, 0, minio.PutObjectOptions{ContentType: "application/octet-stream"})`

It specifies `0` for the filesize -- maybe the intent is to say "unknown size"? According [to the docs](https://min.io/docs/minio/linux/developers/go/API.html#PutObject), `-1` should be used to specify an unknown size (they also warn that it will consume a lot of memory). Elsewhere it looks like [an explicit size](https://github.com/dpb587/metalink/blob/578c916bbfbd4c1469fdd1104c4ab57f55eed3e3/file/url/s3/reference.go#L81) is passed when mirroring files (which upload successfully). I don't know enough about go to know if this is also possible with whatever type of thing is being passed to the repo PutObject method, but I would hope it would be possible? 

Anyways, it sounds like I'm the only person who's ever tried to do this (at least that is what Palermo said 😉 ). Why am I doing this? It feels kind of "wasteful" to spin up a whole repo to store metalink files when I don't really need 'em. That said, for now I'll probably workaround by using a repo, but ... if it's an easy fix, that'd be cool! If not, maybe when I get a chance I will try my hand at a PR.
